<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="PC-20220901VTOZ" name="webtest.logontestcase.logon" tests="7" failures="1" timestamp="20 二月 2025 04:53:13 GMT" time="149.548" errors="0">
  <testcase name="failedPasswordTest" time="19.840" classname="webtest.logontestcase.logon"/>
  <testcase name="failedUsernameTest" time="18.798" classname="webtest.logontestcase.logon">
    <skipped/>
  </testcase> <!-- failedUsernameTest -->
  <testcase name="failedUsernameTest" time="18.597" classname="webtest.logontestcase.logon">
    <skipped/>
  </testcase> <!-- failedUsernameTest -->
  <testcase name="failedUsernameTest" time="28.244" classname="webtest.logontestcase.logon"/>
  <testcase name="failedUsernameTest" time="18.533" classname="webtest.logontestcase.logon">
    <failure type="java.lang.AssertionError" message="expected [账号或密码不正确] but found [账号为4~16位字母、数字或下划线]">
      <![CDATA[java.lang.AssertionError: expected [账号或密码不正确] but found [账号为4~16位字母、数字或下划线]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at webtest.logontestcase.logon.failedUsernameTest(logon.java:93)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper$1.runTestMethod(MethodInvocationHelper.java:230)
at listener.allureReportListener.run(allureReportListener.java:15)
at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:242)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:579)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
    </failure>
  </testcase> <!-- failedUsernameTest -->
  <testcase name="failedUsernameTest" time="18.502" classname="webtest.logontestcase.logon">
    <skipped/>
  </testcase> <!-- failedUsernameTest -->
  <testcase name="logontestcase" time="27.034" classname="webtest.logontestcase.logon"/>
</testsuite> <!-- webtest.logontestcase.logon -->
